spring:


  flyway:
    url: jdbc:h2:~/demodb;AUTO_SERVER=TRUE
    user: sa
    baseline-on-migrate: true
    clean-on-validation-error: true
    locations: classpath:db/migration
    baseline-version: 0

datasource:
  primary:
    jdbc_url: jdbc:h2:~/demodb;AUTO_SERVER=TRUE
    username: sa
